# Generated by Django 2.2.24 on 2022-02-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvapp', '0002_auto_20220212_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
