# Generated by Django 2.2.24 on 2022-02-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvapp', '0005_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
